import Navbar from "./navbar";
import Head from "next/head";
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Head>
        <title>Welcome...</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen border2 border-rose-500">
        <Navbar />
        <div className="h-full pt-16">{children}</div>
      </div>
    </div>
  );
}
